name: Workflow security analysis

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zizmor:
    name: zizmor
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: Spillgebees/admin/.github/workflows/zizmor.yml@06f48d4401dc51168add77e5a0d1b080ea85753d # main
